# -*- coding: utf-8 -*-
"""IBM.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Plv7qLGMDF5EcMPHVw8y16ePdPIBvR7i
"""

!pip install pandas matplotlib

"""IMPORT ALL THE LIBRARIES"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('/content/SampleSuperstore (3).csv')

df.info()

df.describe()

df = df.drop(columns="Postal Code")

df.isna().sum()

df.head()

print(sum(df['Profit']))

"""Sales and Profit by Ship Mode

"""

ship_mode_sales_profit = df.groupby('Ship Mode')['Sales', 'Profit'].sum()
print(ship_mode_sales_profit)

"""Sales and Profit by Category"""

category_sales_profit = df.groupby('Category')['Sales', 'Profit'].sum()
print(category_sales_profit)

"""Top 5 profitable subcategories"""

top_5_profitable_subcategories = df.groupby('Sub-Category')['Profit'].sum().nlargest(5)
print(top_5_profitable_subcategories)

"""Correlation between Sales, Quantity, Discount, and Profit"""

correlation_matrix = df[['Sales', 'Quantity', 'Discount', 'Profit']].corr()
print(correlation_matrix)

"""Visualize sales by category using a bar chart"""

plt.figure(figsize=(10, 6))
df.groupby('Category')['Sales'].sum().plot(kind='bar')
plt.title('Total Sales by Category')
plt.xlabel('Category')
plt.ylabel('Sales')
plt.show()

df.groupby("Category")["Sales"].sum().plot.pie(autopct="%1.0f%%")

plt.figure(figsize=(10, 6))
sns.regplot(x='Discount', y='Profit', data=df, scatter_kws={'alpha':0.3}, line_kws={'color': 'orange'})
plt.title('Profit vs. Discount')
plt.xlabel('Discount')
plt.ylabel('Profit')
plt.show()

"""Proportion of Quantity Sold by Segment"""

segment_quantity = df.groupby('Segment')['Quantity'].sum()
plt.figure(figsize=(8, 8))
plt.pie(segment_quantity, labels=segment_quantity.index, autopct='%1.1f%%', startangle=90, colors=['lightblue', 'lightgreen', 'lightcoral'])
plt.title('Proportion of Quantity Sold by Segment')
plt.axis('equal')
plt.show()

df.groupby("State")["Sales"].sum().plot.bar()

"""Sales by Region"""

plt.figure(figsize=(8, 6))
plt.bar(df['Region'], df['Sales'])
plt.xlabel('Region')
plt.ylabel('Sales')
plt.title('Sales by Region')
plt.show()

"""Profit With Respect To Each Segment"""

df.groupby("Segment")["Profit"].sum().plot.bar()

"""Profit With Respect To Each Category"""

df.groupby("Category")["Profit"].sum().plot.bar()

